spring:
  application:
    name: domain-module
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(23VtkEODP7NFAlIXh6iu3w==)
    url: ENC(xcpdNBbgA3cWXKlrjVOVHiQCCIWuZWy7JKD5qIxMnkBLZsDV2UOzYFr57bZZhEXj)
    password: ENC(Z3bshepqUUYRmo/xDJI/tsLRQ54VFjbS)
  #    url: ENC(cjE9nt26Kyi+TPxF8pPD0RXLenxNaoiIVGzsUxPa3xSwYIxY387damK4Zf7xN8J/p9XO2QWE2lVdkb3LjQSuapA0PEXLPtGf7uHKND0pOultghs/78YfaKv37bR3I8uA)
  #    username: ENC(WEGH/622uWGO/MqSOC6Uw7Vcbb+Ivy+7)
  #    password: ENC(11L+R8sQN5HBKnXMxFpfAm55jSn+gekH)
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      open-in-view: false