server:
  port: 8080

spring:
  profiles:
    include: secret
    active: default
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(23VtkEODP7NFAlIXh6iu3w==)
    url: ENC(xcpdNBbgA3cWXKlrjVOVHiQCCIWuZWy7JKD5qIxMnkBLZsDV2UOzYFr57bZZhEXj)
    password: ENC(Z3bshepqUUYRmo/xDJI/tsLRQ54VFjbS)
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
  redis:
    host: ENC(w9qDnaEabKQ4NbweCUEcxoMp+an+TBDU)
    port: 6378
    password: ENC(IDxTSfQKMZjHv0pDXXf8OGCsgS61Eljt)
  swagger-ui:
    path: ENC(WTBg/5W0RzdfjEYWeHF/lvHH8XFo0FJA0Ue3wuWoTRM=)
    use-root-path: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false

firebase:
  # config: firebase/firebase-dev-admin.json
  scope: ENC(TvK32/6aBLSdr0KU74LEfETuNCh5DAAdh9zNcIlc9YKIiLKzKX5/6Fe38hm7sA1Z/oUcVuxPkoc=)
  config-file: ENC(5K3jHQakQrHvvFg0fY+1V5oTIkU8XXLOINFq3NvyVCjcpgUtOkr7OPvvVPP/gjznb9L50VmrXAmyidlytGL9mVNhiyUPB3HI0bQh4vueg/tLzE3xjZO7IXhtL1NkZC3YXwqehAh8ehtCOQ1leJdiIyO1MThjez1OH9aHE9tc98zCrEnoNe4HppOk+1BFA3gbkAl7eYOxzxnzaSMcHC5xcsc1T6NsvhfbZ+yAYQcZAu9f8JKVLS5mI/1QUksx8vaFTm7p2c7xmTuAJTqB/+AVQpUB8dbbRRfDdWPuueGqZ0PiqfSHCV16Amzhahy45l7u685isZdnoPHYoOxcMrLZZL1tnKep9saii1Fwcm+Y/MXZucxhJGm0t3yYXQ4uBY2efZVbdA+ZEshhoBuvKrkq8AFHQsIR0pg2dmGjONgp7XoBLTLLL95fMG/DAyHK4U4ftJKAm3zb1h1VQ0maIja8HrO9aO7DdPREEnslRuxqJFO/eETqydsgaJLEWrOJDP5/gVynhuq02hf+e8VvkKRum0HgpfiXKU0NACHMttRUfnTv0I9aGLKxkprao/KesjMDFbH4ZaXZ+IHhrF0GRaP13O/l634IEzT9zwqWecuaOOzRJJnR10JwCGm+0bira6TRf8Fgu6BaoWLHbQ8Lc/3Ag+W1njgzrZ0sitpTc0yo0tuI5MGulgZ/h1rqVhaE7R5PMraQT3DIqCDp7I1KPzlQMig4a24KIx3kL2Ke1yUDc3monSGBpBtro1JHufsLT6feseOm4ERbqqHOPVmOlV0CWzF4EsmqFCZHW6jB1KlnxK+q+lfQ3pcBxeJPhyVf5jXt1Xd1bnQO1ssdnpGDPI2LbUrkS5h/PIMtGDZnC0XBr8FGJ0oB+p6mBOqtYbqxl5Kp6XQd6gZEe1Pv2JiukedYNikMVbuintJk8WOtl5wNw2RiU4PUARemlPwXa74hcPZrq1DCLdue7drq6LkVW6jFJw04kRi60gt+LLGYvW6uYlGOOSLAzVDwiJV6qKIvkqkyBhv66anScyROYbFsTy1EULkbcXUBkAdmqyHu5TZSZ34UlBWyTf1GiFFA6eUihawv3JPWn0NdNnnrN35oXakwSTg4sZw+OuvmKfcUcdBO+XceuHzbNBL6z661UlzpNzBQrgdlxopNM0FeJnUUxJxP/kQdItjLDYvwAbuVYmWU5neT9uPIlzyhLUN7KhMspoUcHRBCOwnURRZ7He3QX861aaIX3/3IHPYgl2HhreqGRgIDrRwKu2kZDcvXiNAXeH4r+MvJEA+cQ6phFEIof3Va+r54YAFk8y2Vj2GppvxpFD4B5dKm+d+DcDmDjit6+FC0ZWnlE0VzeYD+vvGIy7wSaumHAlX/bV5sHxxW8RqrsgAAlAn2dhUHWYZKhw83oFu8xsjMUTOzqVcSkIGZzUlyyA+IhJ1AoFQHi+pa/cwn8fv5ULqLHcnINpXkdvM2EIkM/UqHwFJFb3DySZYbHOaXv1s85Uw+U6Keqv3PTjCLRNVb7yWtJZTheMpPH9J/AC/gklAdn+RTsAgZt9IxHZCskPcvQmnSyzzs0qvsIpRxRni+IFTeOez+i9K+9IlTrv84EN0RXOA4yuiCQb4wYQw3ufxW0p1+0P4Ako/KdfIGMhNOnEio0JXTgMEE9yebxrSDa8n04w0rT7pjTuaItONZSFwZBlS2HkEVg4+4iP2kmwca7QyTQmy+luAcWSP2JYzu5dpoGbZxj+MZKX4hVB3o2brOE8cjcEh9+DI363uZWPdM/ZTWM6Lvs/3rrQfZyFjX+sgNWOJE/90CTX90lkb3isKXTJH9Sp6bv0EeMCZ9yN91T8Jgo5A0dQyewy4fpcLqJEeeujU0ADAMGTzrxmTYlW9OPJy3UYVZboc+LRnsLWprgu0FeH5C1H6P/g7D0O0RS4moPNBa3wc88eg14IX+Biq8bHT92hR5pK3u1NAw1uxlWSQw0VMubMdohOKxof2kbzhP5rQyf3JBBfq7KFVG40qi2ySu3w+Eoa+1b3MQxjFlhboTA8e+ylrtSF7a3RjDk19/H9zusycGky1ZqBMARDeyMhm65/zCxWMBp15ZQ9kro7xTkWR4FFvTsHAOmWUOGqg9rscufUqvvAeB6uRIzZNs2h0QLneHzTuvf8Qez/06oTtqHAbfaMgKTunW6PxA+O3E7ykksOOKj9U5yofVtszgNTe4HyF34uG95Y4JcCFNgFZJDVs9fcktUFBRj51uII7EatEMXrWvUDTGGgFdGtjrkwyjAZbHSVwuJG83MiA7v9NafNN9GhXNyEgpb0iQ3RiJBmBE+nADTwQC2fFqgJxFBIXAkRFYNBTLuY5IoL9zXLOwK5nNZwjCK0FWwfS8//3HT9dQVE4FYEFE4YexubRS7Ji/sp8YHgiBVwAH3uqxb3IF8/r3m/cgEQ+Se8sRSb1T8ZfUPHy4zdQezEuQ4xH3I7Kse5apyw/p099NoMNe8HJxQsZklHj7enATr/DFj/2ihcHG37ew7yvIYaRfV2bDWXMrc37dOssEG1htY2mrWhEC3K77XaY0RhBtqdEOf1QEYvP3P4+MxsUizBaHKjCEq2cs4AsaBwhQAGtS0wMlZSHkfmGeCRKfFq/FWfpwQHqkkkzceE8c841nuLl182ReTu6nNOXizm20LJJ+XaKEtJFiI4xf9JFOG7EIBxkIdOe21ZOzXnVyr18UVESetNBhy1pEUj1TABnWfCpIwq+Rx6FjKdFjpJEnuhdnuM5uYitHXbLe70k2TKQvrOAyGzSb434BsZit3AOLMtTuiYNrIIupR7a189ntWRLOG0XtBhv5Bqk/pZ0UGtPXJnvdFtvoe/M3Y89vvwMZ+e4cOIMziovIDgpUo1X5iCdLScdFtc2UAEJ7tVpFdWqPhZpNOh3WIleVE8KHvJDRa1cbiE7Exrc6TC7I3LMb7DyH/X8nK2Y/d8EPvdEBNJgOij+k7PeQxR9e0F/LwmsGywrVofR4tLA/P9Ma2em/o5LuhKKZSXMkn+EJxzOUN1Hl6tiv1XfX1HkLG+dCFt1nqH1tyIrM+pSF1w4tDHRpe3qHaWy4ms7I1znGs27uc9ENS5CluvRdAy0G3dQamvf4WaTUQMXmRrWxb4vH1HHswd22mFq6B5O63w2kpp8Zei4eUa2tuQ==)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

sentry:
  dsn: ENC(kcWB8bBCxkeKlhoM0lJKkfXx29L8hWgX5N03JGF6IQ47OZMC7Fn8IleH+AdjVqFtniKKzqs4yTYsdm2zo9Y0scnN/E/iydqmjU/iVcMjegvYJn/AXZAlRqpU84cAXHNWd4oFcF3Bauc=)
  traces-sample-rate: 1.0

---
spring:
  profiles:
    active: stag

---
spring:
  profiles:
    active: release