server:
  port: 8080

spring:
  profiles:
    include: secret
    active: default

---
spring:
  profiles:
    active: dev

---
spring:
  profiles:
    active: stag

---
spring:
  profiles:
    active: release